/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Event = IDL.Variant({
  'megaminx' : IDL.Null,
  'fiveByFive' : IDL.Null,
  'threeByThreeOneHanded' : IDL.Null,
  'clock' : IDL.Null,
  'threeByThree' : IDL.Null,
  'pyraminx' : IDL.Null,
  'skewb' : IDL.Null,
  'twoByTwo' : IDL.Null,
  'fourByFour' : IDL.Null,
});
export const PaymentConfirmation = IDL.Record({
  'razorpayPaymentId' : IDL.Text,
  'razorpaySignature' : IDL.Text,
  'event' : Event,
  'razorpayOrderId' : IDL.Text,
  'competitionId' : IDL.Nat,
});
export const CompetitionStatus = IDL.Variant({
  'upcoming' : IDL.Null,
  'completed' : IDL.Null,
  'running' : IDL.Null,
});
export const Time = IDL.Int;
export const CompetitionInput = IDL.Record({
  'status' : CompetitionStatus,
  'endDate' : Time,
  'scrambles' : IDL.Vec(IDL.Tuple(IDL.Vec(IDL.Text), Event)),
  'name' : IDL.Text,
  'slug' : IDL.Text,
  'events' : IDL.Vec(Event),
  'entryFee' : IDL.Opt(IDL.Nat),
  'participantLimit' : IDL.Opt(IDL.Nat),
  'startDate' : Time,
});
export const UserProfile = IDL.Record({
  'country' : IDL.Opt(IDL.Text),
  'displayName' : IDL.Text,
  'gender' : IDL.Opt(IDL.Text),
  'mcubesId' : IDL.Text,
});
export const Competition = IDL.Record({
  'id' : IDL.Nat,
  'status' : CompetitionStatus,
  'endDate' : Time,
  'scrambles' : IDL.Vec(IDL.Tuple(IDL.Vec(IDL.Text), Event)),
  'name' : IDL.Text,
  'slug' : IDL.Text,
  'events' : IDL.Vec(Event),
  'entryFee' : IDL.Opt(IDL.Nat),
  'participantLimit' : IDL.Opt(IDL.Nat),
  'startDate' : Time,
});
export const CompetitionPublic = IDL.Record({
  'id' : IDL.Nat,
  'status' : CompetitionStatus,
  'endDate' : Time,
  'name' : IDL.Text,
  'slug' : IDL.Text,
  'events' : IDL.Vec(Event),
  'entryFee' : IDL.Opt(IDL.Nat),
  'participantLimit' : IDL.Opt(IDL.Nat),
  'startDate' : Time,
});
export const SolveStatus = IDL.Variant({
  'in_progress' : IDL.Null,
  'completed' : IDL.Null,
  'not_started' : IDL.Null,
});
export const AttemptInput = IDL.Record({
  'penalty' : IDL.Nat,
  'time' : IDL.Nat,
});
export const ResultInput = IDL.Record({
  'status' : SolveStatus,
  'user' : IDL.Principal,
  'attempts' : IDL.Vec(AttemptInput),
  'event' : Event,
  'competitionId' : IDL.Nat,
});
export const PublicProfileInfo = IDL.Record({
  'country' : IDL.Opt(IDL.Text),
  'displayName' : IDL.Text,
  'gender' : IDL.Opt(IDL.Text),
});
export const PaidEvent = IDL.Record({
  'id' : IDL.Nat,
  'razorpayPaymentId' : IDL.Text,
  'razorpaySignature' : IDL.Text,
  'event' : Event,
  'razorpayOrderId' : IDL.Text,
  'paymentDate' : Time,
  'entryFee' : IDL.Nat,
  'competitionName' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'confirmPayment' : IDL.Func([PaymentConfirmation], [], []),
  'createCompetition' : IDL.Func([CompetitionInput], [IDL.Nat], []),
  'createUserProfile' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'getAllUserPayments' : IDL.Func([], [IDL.Vec(PaymentConfirmation)], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCompetition' : IDL.Func([IDL.Nat], [IDL.Opt(Competition)], ['query']),
  'getCompetitions' : IDL.Func([], [IDL.Vec(CompetitionPublic)], ['query']),
  'getLeaderboard' : IDL.Func(
      [IDL.Nat, Event],
      [IDL.Vec(ResultInput)],
      ['query'],
    ),
  'getMultiplePublicProfiles' : IDL.Func(
      [IDL.Vec(IDL.Principal)],
      [IDL.Vec(IDL.Tuple(IDL.Principal, PublicProfileInfo))],
      ['query'],
    ),
  'getPublicProfileInfo' : IDL.Func(
      [IDL.Principal],
      [PublicProfileInfo],
      ['query'],
    ),
  'getResults' : IDL.Func([IDL.Nat, Event], [IDL.Vec(ResultInput)], ['query']),
  'getUserPaymentHistory' : IDL.Func([], [IDL.Vec(PaidEvent)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserResult' : IDL.Func(
      [IDL.Nat, Event],
      [IDL.Opt(ResultInput)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setUserEmail' : IDL.Func([IDL.Text], [], []),
  'startCompetition' : IDL.Func([IDL.Nat, Event], [], []),
  'submitAttempt' : IDL.Func([IDL.Nat, Event, IDL.Nat, AttemptInput], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Event = IDL.Variant({
    'megaminx' : IDL.Null,
    'fiveByFive' : IDL.Null,
    'threeByThreeOneHanded' : IDL.Null,
    'clock' : IDL.Null,
    'threeByThree' : IDL.Null,
    'pyraminx' : IDL.Null,
    'skewb' : IDL.Null,
    'twoByTwo' : IDL.Null,
    'fourByFour' : IDL.Null,
  });
  const PaymentConfirmation = IDL.Record({
    'razorpayPaymentId' : IDL.Text,
    'razorpaySignature' : IDL.Text,
    'event' : Event,
    'razorpayOrderId' : IDL.Text,
    'competitionId' : IDL.Nat,
  });
  const CompetitionStatus = IDL.Variant({
    'upcoming' : IDL.Null,
    'completed' : IDL.Null,
    'running' : IDL.Null,
  });
  const Time = IDL.Int;
  const CompetitionInput = IDL.Record({
    'status' : CompetitionStatus,
    'endDate' : Time,
    'scrambles' : IDL.Vec(IDL.Tuple(IDL.Vec(IDL.Text), Event)),
    'name' : IDL.Text,
    'slug' : IDL.Text,
    'events' : IDL.Vec(Event),
    'entryFee' : IDL.Opt(IDL.Nat),
    'participantLimit' : IDL.Opt(IDL.Nat),
    'startDate' : Time,
  });
  const UserProfile = IDL.Record({
    'country' : IDL.Opt(IDL.Text),
    'displayName' : IDL.Text,
    'gender' : IDL.Opt(IDL.Text),
    'mcubesId' : IDL.Text,
  });
  const Competition = IDL.Record({
    'id' : IDL.Nat,
    'status' : CompetitionStatus,
    'endDate' : Time,
    'scrambles' : IDL.Vec(IDL.Tuple(IDL.Vec(IDL.Text), Event)),
    'name' : IDL.Text,
    'slug' : IDL.Text,
    'events' : IDL.Vec(Event),
    'entryFee' : IDL.Opt(IDL.Nat),
    'participantLimit' : IDL.Opt(IDL.Nat),
    'startDate' : Time,
  });
  const CompetitionPublic = IDL.Record({
    'id' : IDL.Nat,
    'status' : CompetitionStatus,
    'endDate' : Time,
    'name' : IDL.Text,
    'slug' : IDL.Text,
    'events' : IDL.Vec(Event),
    'entryFee' : IDL.Opt(IDL.Nat),
    'participantLimit' : IDL.Opt(IDL.Nat),
    'startDate' : Time,
  });
  const SolveStatus = IDL.Variant({
    'in_progress' : IDL.Null,
    'completed' : IDL.Null,
    'not_started' : IDL.Null,
  });
  const AttemptInput = IDL.Record({ 'penalty' : IDL.Nat, 'time' : IDL.Nat });
  const ResultInput = IDL.Record({
    'status' : SolveStatus,
    'user' : IDL.Principal,
    'attempts' : IDL.Vec(AttemptInput),
    'event' : Event,
    'competitionId' : IDL.Nat,
  });
  const PublicProfileInfo = IDL.Record({
    'country' : IDL.Opt(IDL.Text),
    'displayName' : IDL.Text,
    'gender' : IDL.Opt(IDL.Text),
  });
  const PaidEvent = IDL.Record({
    'id' : IDL.Nat,
    'razorpayPaymentId' : IDL.Text,
    'razorpaySignature' : IDL.Text,
    'event' : Event,
    'razorpayOrderId' : IDL.Text,
    'paymentDate' : Time,
    'entryFee' : IDL.Nat,
    'competitionName' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'confirmPayment' : IDL.Func([PaymentConfirmation], [], []),
    'createCompetition' : IDL.Func([CompetitionInput], [IDL.Nat], []),
    'createUserProfile' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'getAllUserPayments' : IDL.Func([], [IDL.Vec(PaymentConfirmation)], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCompetition' : IDL.Func([IDL.Nat], [IDL.Opt(Competition)], ['query']),
    'getCompetitions' : IDL.Func([], [IDL.Vec(CompetitionPublic)], ['query']),
    'getLeaderboard' : IDL.Func(
        [IDL.Nat, Event],
        [IDL.Vec(ResultInput)],
        ['query'],
      ),
    'getMultiplePublicProfiles' : IDL.Func(
        [IDL.Vec(IDL.Principal)],
        [IDL.Vec(IDL.Tuple(IDL.Principal, PublicProfileInfo))],
        ['query'],
      ),
    'getPublicProfileInfo' : IDL.Func(
        [IDL.Principal],
        [PublicProfileInfo],
        ['query'],
      ),
    'getResults' : IDL.Func(
        [IDL.Nat, Event],
        [IDL.Vec(ResultInput)],
        ['query'],
      ),
    'getUserPaymentHistory' : IDL.Func([], [IDL.Vec(PaidEvent)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserResult' : IDL.Func(
        [IDL.Nat, Event],
        [IDL.Opt(ResultInput)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setUserEmail' : IDL.Func([IDL.Text], [], []),
    'startCompetition' : IDL.Func([IDL.Nat, Event], [], []),
    'submitAttempt' : IDL.Func([IDL.Nat, Event, IDL.Nat, AttemptInput], [], []),
  });
};

export const init = ({ IDL }) => { return []; };