/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Event = IDL.Variant({
  'megaminx' : IDL.Null,
  'fiveByFive' : IDL.Null,
  'threeByThreeOneHanded' : IDL.Null,
  'clock' : IDL.Null,
  'threeByThree' : IDL.Null,
  'pyraminx' : IDL.Null,
  'skewb' : IDL.Null,
  'twoByTwo' : IDL.Null,
  'fourByFour' : IDL.Null,
});
export const PaymentConfirmation = IDL.Record({
  'razorpayPaymentId' : IDL.Text,
  'razorpaySignature' : IDL.Text,
  'event' : Event,
  'razorpayOrderId' : IDL.Text,
  'competitionId' : IDL.Nat,
});
export const CompetitionStatus = IDL.Variant({
  'upcoming' : IDL.Null,
  'completed' : IDL.Null,
  'running' : IDL.Null,
});
export const Time = IDL.Int;
export const FeeMode = IDL.Variant({
  'perEvent' : IDL.Nat,
  'allEventsFlat' : IDL.Nat,
  'basePlusAdditional' : IDL.Record({
    'baseFee' : IDL.Nat,
    'additionalFee' : IDL.Nat,
  }),
});
export const CompetitionInput = IDL.Record({
  'status' : CompetitionStatus,
  'endDate' : Time,
  'scrambles' : IDL.Vec(IDL.Tuple(IDL.Vec(IDL.Text), Event)),
  'name' : IDL.Text,
  'slug' : IDL.Text,
  'feeMode' : IDL.Opt(FeeMode),
  'events' : IDL.Vec(Event),
  'participantLimit' : IDL.Opt(IDL.Nat),
  'registrationStartDate' : IDL.Opt(Time),
  'startDate' : Time,
});
export const Competition = IDL.Record({
  'id' : IDL.Nat,
  'status' : CompetitionStatus,
  'endDate' : Time,
  'scrambles' : IDL.Vec(IDL.Tuple(IDL.Vec(IDL.Text), Event)),
  'name' : IDL.Text,
  'slug' : IDL.Text,
  'feeMode' : IDL.Opt(FeeMode),
  'isActive' : IDL.Bool,
  'events' : IDL.Vec(Event),
  'isLocked' : IDL.Bool,
  'participantLimit' : IDL.Opt(IDL.Nat),
  'registrationStartDate' : IDL.Opt(Time),
  'startDate' : Time,
});
export const RazorpayOrderRequest = IDL.Record({
  'event' : Event,
  'competitionId' : IDL.Nat,
});
export const RazorpayOrderResponse = IDL.Record({
  'orderId' : IDL.Text,
  'event' : Event,
  'currency' : IDL.Text,
  'amount' : IDL.Nat,
  'competitionName' : IDL.Text,
});
export const SolveStatus = IDL.Variant({
  'in_progress' : IDL.Null,
  'completed' : IDL.Null,
  'not_started' : IDL.Null,
});
export const Attempt = IDL.Record({ 'penalty' : IDL.Nat, 'time' : IDL.Nat });
export const AdminResultEntry = IDL.Record({
  'ao5' : IDL.Opt(IDL.Nat),
  'status' : SolveStatus,
  'user' : IDL.Principal,
  'attempts' : IDL.Vec(Attempt),
  'event' : Event,
  'isHidden' : IDL.Bool,
  'competitionId' : IDL.Nat,
});
export const AdminScrambleView = IDL.Record({
  'id' : IDL.Nat,
  'scrambleRecords' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Bool)),
  'event' : Event,
});
export const CompetitionPublic = IDL.Record({
  'id' : IDL.Nat,
  'status' : CompetitionStatus,
  'endDate' : Time,
  'name' : IDL.Text,
  'slug' : IDL.Text,
  'feeMode' : IDL.Opt(FeeMode),
  'events' : IDL.Vec(Event),
  'participantLimit' : IDL.Opt(IDL.Nat),
  'registrationStartDate' : IDL.Opt(Time),
  'startDate' : Time,
});
export const UserProfile = IDL.Record({
  'country' : IDL.Opt(IDL.Text),
  'displayName' : IDL.Text,
  'gender' : IDL.Opt(IDL.Text),
  'mcubesId' : IDL.Text,
});
export const PublicProfileInfo = IDL.Record({
  'country' : IDL.Opt(IDL.Text),
  'displayName' : IDL.Text,
  'gender' : IDL.Opt(IDL.Text),
});
export const LeaderboardEntry = IDL.Record({
  'ao5' : IDL.Opt(IDL.Nat),
  'bestTime' : IDL.Nat,
  'user' : IDL.Principal,
  'attempts' : IDL.Vec(Attempt),
  'userProfile' : IDL.Opt(PublicProfileInfo),
});
export const CompetitionResult = IDL.Record({
  'ao5' : IDL.Opt(IDL.Nat),
  'status' : SolveStatus,
  'user' : IDL.Principal,
  'attempts' : IDL.Vec(Attempt),
  'event' : Event,
  'userProfile' : IDL.Opt(UserProfile),
});
export const CompetitorResults = IDL.Record({
  'results' : IDL.Vec(CompetitionResult),
  'competitor' : IDL.Principal,
});
export const UserSummary = IDL.Record({
  'principal' : IDL.Principal,
  'isBlocked' : IDL.Bool,
  'email' : IDL.Opt(IDL.Text),
  'profile' : IDL.Opt(UserProfile),
});
export const RazorpayCredentials = IDL.Record({
  'keyId' : IDL.Text,
  'keySecret' : IDL.Text,
});
export const AdminLeaderboardToggleResult = IDL.Record({
  'user' : IDL.Principal,
  'event' : Event,
  'isHidden' : IDL.Bool,
  'competitionId' : IDL.Nat,
});
export const AttemptInput = IDL.Record({
  'penalty' : IDL.Nat,
  'time' : IDL.Nat,
});
export const ResultInput = IDL.Record({
  'ao5' : IDL.Opt(IDL.Nat),
  'status' : SolveStatus,
  'user' : IDL.Principal,
  'attempts' : IDL.Vec(AttemptInput),
  'event' : Event,
  'competitionId' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'blockUser' : IDL.Func([IDL.Principal], [], []),
  'confirmPayment' : IDL.Func([PaymentConfirmation], [], []),
  'createCompetition' : IDL.Func([CompetitionInput], [Competition], []),
  'createRazorpayOrder' : IDL.Func(
      [RazorpayOrderRequest],
      [RazorpayOrderResponse],
      [],
    ),
  'deleteCompetition' : IDL.Func([IDL.Nat], [], []),
  'getAdminResults' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(AdminResultEntry)],
      ['query'],
    ),
  'getAdminScrambleView' : IDL.Func(
      [],
      [IDL.Vec(AdminScrambleView)],
      ['query'],
    ),
  'getAllCompetitions' : IDL.Func([], [IDL.Vec(CompetitionPublic)], ['query']),
  'getBlockedUsers' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCompetition' : IDL.Func([IDL.Nat], [Competition], ['query']),
  'getCompetitionLeaderboard' : IDL.Func(
      [IDL.Nat, Event],
      [IDL.Vec(LeaderboardEntry)],
      ['query'],
    ),
  'getCompetitionResults' : IDL.Func(
      [IDL.Nat, Event],
      [IDL.Vec(CompetitionResult)],
      ['query'],
    ),
  'getCompetitorResults' : IDL.Func(
      [IDL.Principal],
      [CompetitorResults],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserSummaries' : IDL.Func([], [IDL.Vec(UserSummary)], ['query']),
  'hasRazorpayConfig' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setRazorpayCredentials' : IDL.Func([RazorpayCredentials], [], []),
  'startOrResumeCompetitionSession' : IDL.Func(
      [IDL.Nat, Event],
      [IDL.Vec(IDL.Nat8)],
      [],
    ),
  'toggleCompetitionActive' : IDL.Func([IDL.Nat], [], []),
  'toggleCompetitionLock' : IDL.Func([IDL.Nat], [Competition], []),
  'toggleLeaderboardEntryVisibility' : IDL.Func(
      [IDL.Principal, IDL.Nat, Event],
      [AdminLeaderboardToggleResult],
      [],
    ),
  'unblockUser' : IDL.Func([IDL.Principal], [], []),
  'updateCompetitionStatus' : IDL.Func([IDL.Nat, CompetitionStatus], [], []),
  'updateCompetitorResult' : IDL.Func([ResultInput], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Event = IDL.Variant({
    'megaminx' : IDL.Null,
    'fiveByFive' : IDL.Null,
    'threeByThreeOneHanded' : IDL.Null,
    'clock' : IDL.Null,
    'threeByThree' : IDL.Null,
    'pyraminx' : IDL.Null,
    'skewb' : IDL.Null,
    'twoByTwo' : IDL.Null,
    'fourByFour' : IDL.Null,
  });
  const PaymentConfirmation = IDL.Record({
    'razorpayPaymentId' : IDL.Text,
    'razorpaySignature' : IDL.Text,
    'event' : Event,
    'razorpayOrderId' : IDL.Text,
    'competitionId' : IDL.Nat,
  });
  const CompetitionStatus = IDL.Variant({
    'upcoming' : IDL.Null,
    'completed' : IDL.Null,
    'running' : IDL.Null,
  });
  const Time = IDL.Int;
  const FeeMode = IDL.Variant({
    'perEvent' : IDL.Nat,
    'allEventsFlat' : IDL.Nat,
    'basePlusAdditional' : IDL.Record({
      'baseFee' : IDL.Nat,
      'additionalFee' : IDL.Nat,
    }),
  });
  const CompetitionInput = IDL.Record({
    'status' : CompetitionStatus,
    'endDate' : Time,
    'scrambles' : IDL.Vec(IDL.Tuple(IDL.Vec(IDL.Text), Event)),
    'name' : IDL.Text,
    'slug' : IDL.Text,
    'feeMode' : IDL.Opt(FeeMode),
    'events' : IDL.Vec(Event),
    'participantLimit' : IDL.Opt(IDL.Nat),
    'registrationStartDate' : IDL.Opt(Time),
    'startDate' : Time,
  });
  const Competition = IDL.Record({
    'id' : IDL.Nat,
    'status' : CompetitionStatus,
    'endDate' : Time,
    'scrambles' : IDL.Vec(IDL.Tuple(IDL.Vec(IDL.Text), Event)),
    'name' : IDL.Text,
    'slug' : IDL.Text,
    'feeMode' : IDL.Opt(FeeMode),
    'isActive' : IDL.Bool,
    'events' : IDL.Vec(Event),
    'isLocked' : IDL.Bool,
    'participantLimit' : IDL.Opt(IDL.Nat),
    'registrationStartDate' : IDL.Opt(Time),
    'startDate' : Time,
  });
  const RazorpayOrderRequest = IDL.Record({
    'event' : Event,
    'competitionId' : IDL.Nat,
  });
  const RazorpayOrderResponse = IDL.Record({
    'orderId' : IDL.Text,
    'event' : Event,
    'currency' : IDL.Text,
    'amount' : IDL.Nat,
    'competitionName' : IDL.Text,
  });
  const SolveStatus = IDL.Variant({
    'in_progress' : IDL.Null,
    'completed' : IDL.Null,
    'not_started' : IDL.Null,
  });
  const Attempt = IDL.Record({ 'penalty' : IDL.Nat, 'time' : IDL.Nat });
  const AdminResultEntry = IDL.Record({
    'ao5' : IDL.Opt(IDL.Nat),
    'status' : SolveStatus,
    'user' : IDL.Principal,
    'attempts' : IDL.Vec(Attempt),
    'event' : Event,
    'isHidden' : IDL.Bool,
    'competitionId' : IDL.Nat,
  });
  const AdminScrambleView = IDL.Record({
    'id' : IDL.Nat,
    'scrambleRecords' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Bool)),
    'event' : Event,
  });
  const CompetitionPublic = IDL.Record({
    'id' : IDL.Nat,
    'status' : CompetitionStatus,
    'endDate' : Time,
    'name' : IDL.Text,
    'slug' : IDL.Text,
    'feeMode' : IDL.Opt(FeeMode),
    'events' : IDL.Vec(Event),
    'participantLimit' : IDL.Opt(IDL.Nat),
    'registrationStartDate' : IDL.Opt(Time),
    'startDate' : Time,
  });
  const UserProfile = IDL.Record({
    'country' : IDL.Opt(IDL.Text),
    'displayName' : IDL.Text,
    'gender' : IDL.Opt(IDL.Text),
    'mcubesId' : IDL.Text,
  });
  const PublicProfileInfo = IDL.Record({
    'country' : IDL.Opt(IDL.Text),
    'displayName' : IDL.Text,
    'gender' : IDL.Opt(IDL.Text),
  });
  const LeaderboardEntry = IDL.Record({
    'ao5' : IDL.Opt(IDL.Nat),
    'bestTime' : IDL.Nat,
    'user' : IDL.Principal,
    'attempts' : IDL.Vec(Attempt),
    'userProfile' : IDL.Opt(PublicProfileInfo),
  });
  const CompetitionResult = IDL.Record({
    'ao5' : IDL.Opt(IDL.Nat),
    'status' : SolveStatus,
    'user' : IDL.Principal,
    'attempts' : IDL.Vec(Attempt),
    'event' : Event,
    'userProfile' : IDL.Opt(UserProfile),
  });
  const CompetitorResults = IDL.Record({
    'results' : IDL.Vec(CompetitionResult),
    'competitor' : IDL.Principal,
  });
  const UserSummary = IDL.Record({
    'principal' : IDL.Principal,
    'isBlocked' : IDL.Bool,
    'email' : IDL.Opt(IDL.Text),
    'profile' : IDL.Opt(UserProfile),
  });
  const RazorpayCredentials = IDL.Record({
    'keyId' : IDL.Text,
    'keySecret' : IDL.Text,
  });
  const AdminLeaderboardToggleResult = IDL.Record({
    'user' : IDL.Principal,
    'event' : Event,
    'isHidden' : IDL.Bool,
    'competitionId' : IDL.Nat,
  });
  const AttemptInput = IDL.Record({ 'penalty' : IDL.Nat, 'time' : IDL.Nat });
  const ResultInput = IDL.Record({
    'ao5' : IDL.Opt(IDL.Nat),
    'status' : SolveStatus,
    'user' : IDL.Principal,
    'attempts' : IDL.Vec(AttemptInput),
    'event' : Event,
    'competitionId' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'blockUser' : IDL.Func([IDL.Principal], [], []),
    'confirmPayment' : IDL.Func([PaymentConfirmation], [], []),
    'createCompetition' : IDL.Func([CompetitionInput], [Competition], []),
    'createRazorpayOrder' : IDL.Func(
        [RazorpayOrderRequest],
        [RazorpayOrderResponse],
        [],
      ),
    'deleteCompetition' : IDL.Func([IDL.Nat], [], []),
    'getAdminResults' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(AdminResultEntry)],
        ['query'],
      ),
    'getAdminScrambleView' : IDL.Func(
        [],
        [IDL.Vec(AdminScrambleView)],
        ['query'],
      ),
    'getAllCompetitions' : IDL.Func(
        [],
        [IDL.Vec(CompetitionPublic)],
        ['query'],
      ),
    'getBlockedUsers' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCompetition' : IDL.Func([IDL.Nat], [Competition], ['query']),
    'getCompetitionLeaderboard' : IDL.Func(
        [IDL.Nat, Event],
        [IDL.Vec(LeaderboardEntry)],
        ['query'],
      ),
    'getCompetitionResults' : IDL.Func(
        [IDL.Nat, Event],
        [IDL.Vec(CompetitionResult)],
        ['query'],
      ),
    'getCompetitorResults' : IDL.Func(
        [IDL.Principal],
        [CompetitorResults],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserSummaries' : IDL.Func([], [IDL.Vec(UserSummary)], ['query']),
    'hasRazorpayConfig' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setRazorpayCredentials' : IDL.Func([RazorpayCredentials], [], []),
    'startOrResumeCompetitionSession' : IDL.Func(
        [IDL.Nat, Event],
        [IDL.Vec(IDL.Nat8)],
        [],
      ),
    'toggleCompetitionActive' : IDL.Func([IDL.Nat], [], []),
    'toggleCompetitionLock' : IDL.Func([IDL.Nat], [Competition], []),
    'toggleLeaderboardEntryVisibility' : IDL.Func(
        [IDL.Principal, IDL.Nat, Event],
        [AdminLeaderboardToggleResult],
        [],
      ),
    'unblockUser' : IDL.Func([IDL.Principal], [], []),
    'updateCompetitionStatus' : IDL.Func([IDL.Nat, CompetitionStatus], [], []),
    'updateCompetitorResult' : IDL.Func([ResultInput], [], []),
  });
};

export const init = ({ IDL }) => { return []; };