/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Event = IDL.Variant({
  'megaminx' : IDL.Null,
  'fiveByFive' : IDL.Null,
  'threeByThreeOneHanded' : IDL.Null,
  'clock' : IDL.Null,
  'threeByThree' : IDL.Null,
  'pyraminx' : IDL.Null,
  'skewb' : IDL.Null,
  'twoByTwo' : IDL.Null,
  'fourByFour' : IDL.Null,
});
export const PaymentConfirmation = IDL.Record({
  'razorpayPaymentId' : IDL.Text,
  'razorpaySignature' : IDL.Text,
  'event' : Event,
  'razorpayOrderId' : IDL.Text,
  'competitionId' : IDL.Nat,
});
export const RazorpayOrderRequest = IDL.Record({
  'event' : Event,
  'competitionId' : IDL.Nat,
});
export const RazorpayOrderResponse = IDL.Record({
  'orderId' : IDL.Text,
  'event' : Event,
  'currency' : IDL.Text,
  'amount' : IDL.Nat,
  'competitionName' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'country' : IDL.Opt(IDL.Text),
  'displayName' : IDL.Text,
  'gender' : IDL.Opt(IDL.Text),
  'mcubesId' : IDL.Text,
});
export const SolveStatus = IDL.Variant({
  'in_progress' : IDL.Null,
  'completed' : IDL.Null,
  'not_started' : IDL.Null,
});
export const Attempt = IDL.Record({ 'penalty' : IDL.Nat, 'time' : IDL.Nat });
export const CompetitionResult = IDL.Record({
  'status' : SolveStatus,
  'user' : IDL.Principal,
  'attempts' : IDL.Vec(Attempt),
  'event' : Event,
  'userProfile' : IDL.Opt(UserProfile),
});
export const AttemptInput = IDL.Record({
  'penalty' : IDL.Nat,
  'time' : IDL.Nat,
});
export const ResultInput = IDL.Record({
  'status' : SolveStatus,
  'user' : IDL.Principal,
  'attempts' : IDL.Vec(AttemptInput),
  'event' : Event,
  'competitionId' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'confirmPayment' : IDL.Func([PaymentConfirmation], [], []),
  'createRazorpayOrder' : IDL.Func(
      [RazorpayOrderRequest],
      [RazorpayOrderResponse],
      [],
    ),
  'duplicateCompetition' : IDL.Func([IDL.Nat], [IDL.Nat], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCompetitionResults' : IDL.Func(
      [IDL.Nat, Event],
      [IDL.Vec(CompetitionResult)],
      ['query'],
    ),
  'getRazorpayKeyId' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isRazorpayConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setRazorpayCredentials' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'startSolveSession' : IDL.Func([IDL.Nat, Event], [], []),
  'submitResult' : IDL.Func([ResultInput], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Event = IDL.Variant({
    'megaminx' : IDL.Null,
    'fiveByFive' : IDL.Null,
    'threeByThreeOneHanded' : IDL.Null,
    'clock' : IDL.Null,
    'threeByThree' : IDL.Null,
    'pyraminx' : IDL.Null,
    'skewb' : IDL.Null,
    'twoByTwo' : IDL.Null,
    'fourByFour' : IDL.Null,
  });
  const PaymentConfirmation = IDL.Record({
    'razorpayPaymentId' : IDL.Text,
    'razorpaySignature' : IDL.Text,
    'event' : Event,
    'razorpayOrderId' : IDL.Text,
    'competitionId' : IDL.Nat,
  });
  const RazorpayOrderRequest = IDL.Record({
    'event' : Event,
    'competitionId' : IDL.Nat,
  });
  const RazorpayOrderResponse = IDL.Record({
    'orderId' : IDL.Text,
    'event' : Event,
    'currency' : IDL.Text,
    'amount' : IDL.Nat,
    'competitionName' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'country' : IDL.Opt(IDL.Text),
    'displayName' : IDL.Text,
    'gender' : IDL.Opt(IDL.Text),
    'mcubesId' : IDL.Text,
  });
  const SolveStatus = IDL.Variant({
    'in_progress' : IDL.Null,
    'completed' : IDL.Null,
    'not_started' : IDL.Null,
  });
  const Attempt = IDL.Record({ 'penalty' : IDL.Nat, 'time' : IDL.Nat });
  const CompetitionResult = IDL.Record({
    'status' : SolveStatus,
    'user' : IDL.Principal,
    'attempts' : IDL.Vec(Attempt),
    'event' : Event,
    'userProfile' : IDL.Opt(UserProfile),
  });
  const AttemptInput = IDL.Record({ 'penalty' : IDL.Nat, 'time' : IDL.Nat });
  const ResultInput = IDL.Record({
    'status' : SolveStatus,
    'user' : IDL.Principal,
    'attempts' : IDL.Vec(AttemptInput),
    'event' : Event,
    'competitionId' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'confirmPayment' : IDL.Func([PaymentConfirmation], [], []),
    'createRazorpayOrder' : IDL.Func(
        [RazorpayOrderRequest],
        [RazorpayOrderResponse],
        [],
      ),
    'duplicateCompetition' : IDL.Func([IDL.Nat], [IDL.Nat], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCompetitionResults' : IDL.Func(
        [IDL.Nat, Event],
        [IDL.Vec(CompetitionResult)],
        ['query'],
      ),
    'getRazorpayKeyId' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isRazorpayConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setRazorpayCredentials' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'startSolveSession' : IDL.Func([IDL.Nat, Event], [], []),
    'submitResult' : IDL.Func([ResultInput], [], []),
  });
};

export const init = ({ IDL }) => { return []; };