/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ResultInput {
    ao5?: bigint;
    status: SolveStatus;
    user: Principal;
    attempts: Array<AttemptInput>;
    event: Event;
    competitionId: bigint;
}
export interface RazorpayCredentials {
    keyId: string;
    keySecret: string;
}
export type Time = bigint;
export interface PublicProfileInfo {
    country?: string;
    displayName: string;
    gender?: string;
}
export interface RazorpayOrderRequest {
    event: Event;
    competitionId: bigint;
}
export interface LeaderboardEntry {
    ao5?: bigint;
    bestTime: bigint;
    user: Principal;
    attempts: Array<Attempt>;
    userProfile?: PublicProfileInfo;
}
export type FeeMode = {
    __kind__: "perEvent";
    perEvent: bigint;
} | {
    __kind__: "allEventsFlat";
    allEventsFlat: bigint;
} | {
    __kind__: "basePlusAdditional";
    basePlusAdditional: {
        baseFee: bigint;
        additionalFee: bigint;
    };
};
export interface CompetitorResults {
    results: Array<CompetitionResult>;
    competitor: Principal;
}
export interface CompetitionResult {
    ao5?: bigint;
    status: SolveStatus;
    user: Principal;
    attempts: Array<Attempt>;
    event: Event;
    userProfile?: UserProfile;
}
export interface CompetitionPublic {
    id: bigint;
    status: CompetitionStatus;
    endDate: Time;
    name: string;
    slug: string;
    feeMode?: FeeMode;
    events: Array<Event>;
    participantLimit?: bigint;
    registrationStartDate?: Time;
    startDate: Time;
}
export interface CompetitionInput {
    status: CompetitionStatus;
    endDate: Time;
    scrambles: Array<[Array<string>, Event]>;
    name: string;
    slug: string;
    feeMode?: FeeMode;
    events: Array<Event>;
    participantLimit?: bigint;
    registrationStartDate?: Time;
    startDate: Time;
}
export interface PaymentConfirmation {
    razorpayPaymentId: string;
    razorpaySignature: string;
    event: Event;
    razorpayOrderId: string;
    competitionId: bigint;
}
export interface AttemptInput {
    penalty: bigint;
    time: bigint;
}
export interface RazorpayOrderResponse {
    orderId: string;
    event: Event;
    currency: string;
    amount: bigint;
    competitionName: string;
}
export interface AdminScrambleView {
    id: bigint;
    scrambleRecords: Array<[string, boolean]>;
    event: Event;
}
export interface AdminResultEntry {
    ao5?: bigint;
    status: SolveStatus;
    user: Principal;
    attempts: Array<Attempt>;
    event: Event;
    isHidden: boolean;
    competitionId: bigint;
}
export interface UserSummary {
    principal: Principal;
    isBlocked: boolean;
    email?: string;
    profile?: UserProfile;
}
export interface Competition {
    id: bigint;
    status: CompetitionStatus;
    endDate: Time;
    scrambles: Array<[Array<string>, Event]>;
    name: string;
    slug: string;
    feeMode?: FeeMode;
    isActive: boolean;
    events: Array<Event>;
    isLocked: boolean;
    participantLimit?: bigint;
    registrationStartDate?: Time;
    startDate: Time;
}
export interface AdminLeaderboardToggleResult {
    user: Principal;
    event: Event;
    isHidden: boolean;
    competitionId: bigint;
}
export interface Attempt {
    penalty: bigint;
    time: bigint;
}
export interface UserProfile {
    country?: string;
    displayName: string;
    gender?: string;
    mcubesId: string;
}
export enum CompetitionStatus {
    upcoming = "upcoming",
    completed = "completed",
    running = "running"
}
export enum Event {
    megaminx = "megaminx",
    fiveByFive = "fiveByFive",
    threeByThreeOneHanded = "threeByThreeOneHanded",
    clock = "clock",
    threeByThree = "threeByThree",
    pyraminx = "pyraminx",
    skewb = "skewb",
    twoByTwo = "twoByTwo",
    fourByFour = "fourByFour"
}
export enum SolveStatus {
    in_progress = "in_progress",
    completed = "completed",
    not_started = "not_started"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    blockUser(target: Principal): Promise<void>;
    confirmPayment(confirmation: PaymentConfirmation): Promise<void>;
    createCompetition(competition: CompetitionInput): Promise<Competition>;
    createRazorpayOrder(request: RazorpayOrderRequest): Promise<RazorpayOrderResponse>;
    deleteCompetition(competitionId: bigint): Promise<void>;
    getAdminResults(competitionId: bigint): Promise<Array<AdminResultEntry>>;
    getAdminScrambleView(): Promise<Array<AdminScrambleView>>;
    getAllCompetitions(): Promise<Array<CompetitionPublic>>;
    getBlockedUsers(): Promise<Array<Principal>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCompetition(competitionId: bigint): Promise<Competition>;
    getCompetitionLeaderboard(competitionId: bigint, event: Event): Promise<Array<LeaderboardEntry>>;
    getCompetitionResults(competitionId: bigint, event: Event): Promise<Array<CompetitionResult>>;
    getCompetitorResults(competitor: Principal): Promise<CompetitorResults>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getUserSummaries(): Promise<Array<UserSummary>>;
    hasRazorpayConfig(): Promise<boolean>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setRazorpayCredentials(credentials: RazorpayCredentials): Promise<void>;
    startOrResumeCompetitionSession(competitionId: bigint, event: Event): Promise<Uint8Array>;
    toggleCompetitionActive(competitionId: bigint): Promise<void>;
    toggleCompetitionLock(competitionId: bigint): Promise<Competition>;
    toggleLeaderboardEntryVisibility(user: Principal, competitionId: bigint, event: Event): Promise<AdminLeaderboardToggleResult>;
    unblockUser(target: Principal): Promise<void>;
    updateCompetitionStatus(competitionId: bigint, status: CompetitionStatus): Promise<void>;
    updateCompetitorResult(updatedResult: ResultInput): Promise<void>;
}
import type { AdminLeaderboardToggleResult as _AdminLeaderboardToggleResult, AdminResultEntry as _AdminResultEntry, AdminScrambleView as _AdminScrambleView, Attempt as _Attempt, AttemptInput as _AttemptInput, Competition as _Competition, CompetitionInput as _CompetitionInput, CompetitionPublic as _CompetitionPublic, CompetitionResult as _CompetitionResult, CompetitionStatus as _CompetitionStatus, CompetitorResults as _CompetitorResults, Event as _Event, FeeMode as _FeeMode, LeaderboardEntry as _LeaderboardEntry, PaymentConfirmation as _PaymentConfirmation, PublicProfileInfo as _PublicProfileInfo, RazorpayOrderRequest as _RazorpayOrderRequest, RazorpayOrderResponse as _RazorpayOrderResponse, ResultInput as _ResultInput, SolveStatus as _SolveStatus, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, UserSummary as _UserSummary } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async blockUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.blockUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.blockUser(arg0);
            return result;
        }
    }
    async confirmPayment(arg0: PaymentConfirmation): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.confirmPayment(to_candid_PaymentConfirmation_n3(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.confirmPayment(to_candid_PaymentConfirmation_n3(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createCompetition(arg0: CompetitionInput): Promise<Competition> {
        if (this.processError) {
            try {
                const result = await this.actor.createCompetition(to_candid_CompetitionInput_n7(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Competition_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCompetition(to_candid_CompetitionInput_n7(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Competition_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async createRazorpayOrder(arg0: RazorpayOrderRequest): Promise<RazorpayOrderResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.createRazorpayOrder(to_candid_RazorpayOrderRequest_n30(this._uploadFile, this._downloadFile, arg0));
                return from_candid_RazorpayOrderResponse_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createRazorpayOrder(to_candid_RazorpayOrderRequest_n30(this._uploadFile, this._downloadFile, arg0));
            return from_candid_RazorpayOrderResponse_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteCompetition(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCompetition(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCompetition(arg0);
            return result;
        }
    }
    async getAdminResults(arg0: bigint): Promise<Array<AdminResultEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminResults(arg0);
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminResults(arg0);
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAdminScrambleView(): Promise<Array<AdminScrambleView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminScrambleView();
                return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminScrambleView();
            return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllCompetitions(): Promise<Array<CompetitionPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCompetitions();
                return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCompetitions();
            return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBlockedUsers(): Promise<Array<Principal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBlockedUsers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBlockedUsers();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCompetition(arg0: bigint): Promise<Competition> {
        if (this.processError) {
            try {
                const result = await this.actor.getCompetition(arg0);
                return from_candid_Competition_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCompetition(arg0);
            return from_candid_Competition_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCompetitionLeaderboard(arg0: bigint, arg1: Event): Promise<Array<LeaderboardEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCompetitionLeaderboard(arg0, to_candid_Event_n5(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCompetitionLeaderboard(arg0, to_candid_Event_n5(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCompetitionResults(arg0: bigint, arg1: Event): Promise<Array<CompetitionResult>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCompetitionResults(arg0, to_candid_Event_n5(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n57(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCompetitionResults(arg0, to_candid_Event_n5(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n57(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCompetitorResults(arg0: Principal): Promise<CompetitorResults> {
        if (this.processError) {
            try {
                const result = await this.actor.getCompetitorResults(arg0);
                return from_candid_CompetitorResults_n60(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCompetitorResults(arg0);
            return from_candid_CompetitorResults_n60(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserSummaries(): Promise<Array<UserSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserSummaries();
                return from_candid_vec_n62(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserSummaries();
            return from_candid_vec_n62(this._uploadFile, this._downloadFile, result);
        }
    }
    async hasRazorpayConfig(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.hasRazorpayConfig();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.hasRazorpayConfig();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n65(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n65(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setRazorpayCredentials(arg0: RazorpayCredentials): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setRazorpayCredentials(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setRazorpayCredentials(arg0);
            return result;
        }
    }
    async startOrResumeCompetitionSession(arg0: bigint, arg1: Event): Promise<Uint8Array> {
        if (this.processError) {
            try {
                const result = await this.actor.startOrResumeCompetitionSession(arg0, to_candid_Event_n5(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.startOrResumeCompetitionSession(arg0, to_candid_Event_n5(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async toggleCompetitionActive(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleCompetitionActive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleCompetitionActive(arg0);
            return result;
        }
    }
    async toggleCompetitionLock(arg0: bigint): Promise<Competition> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleCompetitionLock(arg0);
                return from_candid_Competition_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleCompetitionLock(arg0);
            return from_candid_Competition_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async toggleLeaderboardEntryVisibility(arg0: Principal, arg1: bigint, arg2: Event): Promise<AdminLeaderboardToggleResult> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleLeaderboardEntryVisibility(arg0, arg1, to_candid_Event_n5(this._uploadFile, this._downloadFile, arg2));
                return from_candid_AdminLeaderboardToggleResult_n67(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleLeaderboardEntryVisibility(arg0, arg1, to_candid_Event_n5(this._uploadFile, this._downloadFile, arg2));
            return from_candid_AdminLeaderboardToggleResult_n67(this._uploadFile, this._downloadFile, result);
        }
    }
    async unblockUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unblockUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unblockUser(arg0);
            return result;
        }
    }
    async updateCompetitionStatus(arg0: bigint, arg1: CompetitionStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCompetitionStatus(arg0, to_candid_CompetitionStatus_n9(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCompetitionStatus(arg0, to_candid_CompetitionStatus_n9(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateCompetitorResult(arg0: ResultInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCompetitorResult(to_candid_ResultInput_n69(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCompetitorResult(to_candid_ResultInput_n69(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_AdminLeaderboardToggleResult_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AdminLeaderboardToggleResult): AdminLeaderboardToggleResult {
    return from_candid_record_n68(_uploadFile, _downloadFile, value);
}
function from_candid_AdminResultEntry_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AdminResultEntry): AdminResultEntry {
    return from_candid_record_n36(_uploadFile, _downloadFile, value);
}
function from_candid_AdminScrambleView_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AdminScrambleView): AdminScrambleView {
    return from_candid_record_n41(_uploadFile, _downloadFile, value);
}
function from_candid_CompetitionPublic_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CompetitionPublic): CompetitionPublic {
    return from_candid_record_n44(_uploadFile, _downloadFile, value);
}
function from_candid_CompetitionResult_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CompetitionResult): CompetitionResult {
    return from_candid_record_n59(_uploadFile, _downloadFile, value);
}
function from_candid_CompetitionStatus_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CompetitionStatus): CompetitionStatus {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_Competition_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Competition): Competition {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_CompetitorResults_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CompetitorResults): CompetitorResults {
    return from_candid_record_n61(_uploadFile, _downloadFile, value);
}
function from_candid_Event_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Event): Event {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_FeeMode_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FeeMode): FeeMode {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_LeaderboardEntry_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LeaderboardEntry): LeaderboardEntry {
    return from_candid_record_n53(_uploadFile, _downloadFile, value);
}
function from_candid_PublicProfileInfo_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PublicProfileInfo): PublicProfileInfo {
    return from_candid_record_n56(_uploadFile, _downloadFile, value);
}
function from_candid_RazorpayOrderResponse_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RazorpayOrderResponse): RazorpayOrderResponse {
    return from_candid_record_n33(_uploadFile, _downloadFile, value);
}
function from_candid_SolveStatus_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SolveStatus): SolveStatus {
    return from_candid_variant_n38(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n47(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n50(_uploadFile, _downloadFile, value);
}
function from_candid_UserSummary_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserSummary): UserSummary {
    return from_candid_record_n64(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_FeeMode]): FeeMode | null {
    return value.length === 0 ? null : from_candid_FeeMode_n25(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n46(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PublicProfileInfo]): PublicProfileInfo | null {
    return value.length === 0 ? null : from_candid_PublicProfileInfo_n55(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _CompetitionStatus;
    endDate: _Time;
    scrambles: Array<[Array<string>, _Event]>;
    name: string;
    slug: string;
    feeMode: [] | [_FeeMode];
    isActive: boolean;
    events: Array<_Event>;
    isLocked: boolean;
    participantLimit: [] | [bigint];
    registrationStartDate: [] | [_Time];
    startDate: _Time;
}): {
    id: bigint;
    status: CompetitionStatus;
    endDate: Time;
    scrambles: Array<[Array<string>, Event]>;
    name: string;
    slug: string;
    feeMode?: FeeMode;
    isActive: boolean;
    events: Array<Event>;
    isLocked: boolean;
    participantLimit?: bigint;
    registrationStartDate?: Time;
    startDate: Time;
} {
    return {
        id: value.id,
        status: from_candid_CompetitionStatus_n18(_uploadFile, _downloadFile, value.status),
        endDate: value.endDate,
        scrambles: from_candid_vec_n20(_uploadFile, _downloadFile, value.scrambles),
        name: value.name,
        slug: value.slug,
        feeMode: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.feeMode)),
        isActive: value.isActive,
        events: from_candid_vec_n27(_uploadFile, _downloadFile, value.events),
        isLocked: value.isLocked,
        participantLimit: record_opt_to_undefined(from_candid_opt_n28(_uploadFile, _downloadFile, value.participantLimit)),
        registrationStartDate: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.registrationStartDate)),
        startDate: value.startDate
    };
}
function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    orderId: string;
    event: _Event;
    currency: string;
    amount: bigint;
    competitionName: string;
}): {
    orderId: string;
    event: Event;
    currency: string;
    amount: bigint;
    competitionName: string;
} {
    return {
        orderId: value.orderId,
        event: from_candid_Event_n22(_uploadFile, _downloadFile, value.event),
        currency: value.currency,
        amount: value.amount,
        competitionName: value.competitionName
    };
}
function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ao5: [] | [bigint];
    status: _SolveStatus;
    user: Principal;
    attempts: Array<_Attempt>;
    event: _Event;
    isHidden: boolean;
    competitionId: bigint;
}): {
    ao5?: bigint;
    status: SolveStatus;
    user: Principal;
    attempts: Array<Attempt>;
    event: Event;
    isHidden: boolean;
    competitionId: bigint;
} {
    return {
        ao5: record_opt_to_undefined(from_candid_opt_n28(_uploadFile, _downloadFile, value.ao5)),
        status: from_candid_SolveStatus_n37(_uploadFile, _downloadFile, value.status),
        user: value.user,
        attempts: value.attempts,
        event: from_candid_Event_n22(_uploadFile, _downloadFile, value.event),
        isHidden: value.isHidden,
        competitionId: value.competitionId
    };
}
function from_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    scrambleRecords: Array<[string, boolean]>;
    event: _Event;
}): {
    id: bigint;
    scrambleRecords: Array<[string, boolean]>;
    event: Event;
} {
    return {
        id: value.id,
        scrambleRecords: value.scrambleRecords,
        event: from_candid_Event_n22(_uploadFile, _downloadFile, value.event)
    };
}
function from_candid_record_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _CompetitionStatus;
    endDate: _Time;
    name: string;
    slug: string;
    feeMode: [] | [_FeeMode];
    events: Array<_Event>;
    participantLimit: [] | [bigint];
    registrationStartDate: [] | [_Time];
    startDate: _Time;
}): {
    id: bigint;
    status: CompetitionStatus;
    endDate: Time;
    name: string;
    slug: string;
    feeMode?: FeeMode;
    events: Array<Event>;
    participantLimit?: bigint;
    registrationStartDate?: Time;
    startDate: Time;
} {
    return {
        id: value.id,
        status: from_candid_CompetitionStatus_n18(_uploadFile, _downloadFile, value.status),
        endDate: value.endDate,
        name: value.name,
        slug: value.slug,
        feeMode: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.feeMode)),
        events: from_candid_vec_n27(_uploadFile, _downloadFile, value.events),
        participantLimit: record_opt_to_undefined(from_candid_opt_n28(_uploadFile, _downloadFile, value.participantLimit)),
        registrationStartDate: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.registrationStartDate)),
        startDate: value.startDate
    };
}
function from_candid_record_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    country: [] | [string];
    displayName: string;
    gender: [] | [string];
    mcubesId: string;
}): {
    country?: string;
    displayName: string;
    gender?: string;
    mcubesId: string;
} {
    return {
        country: record_opt_to_undefined(from_candid_opt_n48(_uploadFile, _downloadFile, value.country)),
        displayName: value.displayName,
        gender: record_opt_to_undefined(from_candid_opt_n48(_uploadFile, _downloadFile, value.gender)),
        mcubesId: value.mcubesId
    };
}
function from_candid_record_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ao5: [] | [bigint];
    bestTime: bigint;
    user: Principal;
    attempts: Array<_Attempt>;
    userProfile: [] | [_PublicProfileInfo];
}): {
    ao5?: bigint;
    bestTime: bigint;
    user: Principal;
    attempts: Array<Attempt>;
    userProfile?: PublicProfileInfo;
} {
    return {
        ao5: record_opt_to_undefined(from_candid_opt_n28(_uploadFile, _downloadFile, value.ao5)),
        bestTime: value.bestTime,
        user: value.user,
        attempts: value.attempts,
        userProfile: record_opt_to_undefined(from_candid_opt_n54(_uploadFile, _downloadFile, value.userProfile))
    };
}
function from_candid_record_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    country: [] | [string];
    displayName: string;
    gender: [] | [string];
}): {
    country?: string;
    displayName: string;
    gender?: string;
} {
    return {
        country: record_opt_to_undefined(from_candid_opt_n48(_uploadFile, _downloadFile, value.country)),
        displayName: value.displayName,
        gender: record_opt_to_undefined(from_candid_opt_n48(_uploadFile, _downloadFile, value.gender))
    };
}
function from_candid_record_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ao5: [] | [bigint];
    status: _SolveStatus;
    user: Principal;
    attempts: Array<_Attempt>;
    event: _Event;
    userProfile: [] | [_UserProfile];
}): {
    ao5?: bigint;
    status: SolveStatus;
    user: Principal;
    attempts: Array<Attempt>;
    event: Event;
    userProfile?: UserProfile;
} {
    return {
        ao5: record_opt_to_undefined(from_candid_opt_n28(_uploadFile, _downloadFile, value.ao5)),
        status: from_candid_SolveStatus_n37(_uploadFile, _downloadFile, value.status),
        user: value.user,
        attempts: value.attempts,
        event: from_candid_Event_n22(_uploadFile, _downloadFile, value.event),
        userProfile: record_opt_to_undefined(from_candid_opt_n45(_uploadFile, _downloadFile, value.userProfile))
    };
}
function from_candid_record_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    results: Array<_CompetitionResult>;
    competitor: Principal;
}): {
    results: Array<CompetitionResult>;
    competitor: Principal;
} {
    return {
        results: from_candid_vec_n57(_uploadFile, _downloadFile, value.results),
        competitor: value.competitor
    };
}
function from_candid_record_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    principal: Principal;
    isBlocked: boolean;
    email: [] | [string];
    profile: [] | [_UserProfile];
}): {
    principal: Principal;
    isBlocked: boolean;
    email?: string;
    profile?: UserProfile;
} {
    return {
        principal: value.principal,
        isBlocked: value.isBlocked,
        email: record_opt_to_undefined(from_candid_opt_n48(_uploadFile, _downloadFile, value.email)),
        profile: record_opt_to_undefined(from_candid_opt_n45(_uploadFile, _downloadFile, value.profile))
    };
}
function from_candid_record_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    user: Principal;
    event: _Event;
    isHidden: boolean;
    competitionId: bigint;
}): {
    user: Principal;
    event: Event;
    isHidden: boolean;
    competitionId: bigint;
} {
    return {
        user: value.user,
        event: from_candid_Event_n22(_uploadFile, _downloadFile, value.event),
        isHidden: value.isHidden,
        competitionId: value.competitionId
    };
}
function from_candid_tuple_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [Array<string>, _Event]): [Array<string>, Event] {
    return [
        value[0],
        from_candid_Event_n22(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    upcoming: null;
} | {
    completed: null;
} | {
    running: null;
}): CompetitionStatus {
    return "upcoming" in value ? CompetitionStatus.upcoming : "completed" in value ? CompetitionStatus.completed : "running" in value ? CompetitionStatus.running : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    megaminx: null;
} | {
    fiveByFive: null;
} | {
    threeByThreeOneHanded: null;
} | {
    clock: null;
} | {
    threeByThree: null;
} | {
    pyraminx: null;
} | {
    skewb: null;
} | {
    twoByTwo: null;
} | {
    fourByFour: null;
}): Event {
    return "megaminx" in value ? Event.megaminx : "fiveByFive" in value ? Event.fiveByFive : "threeByThreeOneHanded" in value ? Event.threeByThreeOneHanded : "clock" in value ? Event.clock : "threeByThree" in value ? Event.threeByThree : "pyraminx" in value ? Event.pyraminx : "skewb" in value ? Event.skewb : "twoByTwo" in value ? Event.twoByTwo : "fourByFour" in value ? Event.fourByFour : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    perEvent: bigint;
} | {
    allEventsFlat: bigint;
} | {
    basePlusAdditional: {
        baseFee: bigint;
        additionalFee: bigint;
    };
}): {
    __kind__: "perEvent";
    perEvent: bigint;
} | {
    __kind__: "allEventsFlat";
    allEventsFlat: bigint;
} | {
    __kind__: "basePlusAdditional";
    basePlusAdditional: {
        baseFee: bigint;
        additionalFee: bigint;
    };
} {
    return "perEvent" in value ? {
        __kind__: "perEvent",
        perEvent: value.perEvent
    } : "allEventsFlat" in value ? {
        __kind__: "allEventsFlat",
        allEventsFlat: value.allEventsFlat
    } : "basePlusAdditional" in value ? {
        __kind__: "basePlusAdditional",
        basePlusAdditional: value.basePlusAdditional
    } : value;
}
function from_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    in_progress: null;
} | {
    completed: null;
} | {
    not_started: null;
}): SolveStatus {
    return "in_progress" in value ? SolveStatus.in_progress : "completed" in value ? SolveStatus.completed : "not_started" in value ? SolveStatus.not_started : value;
}
function from_candid_variant_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[Array<string>, _Event]>): Array<[Array<string>, Event]> {
    return value.map((x)=>from_candid_tuple_n21(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Event>): Array<Event> {
    return value.map((x)=>from_candid_Event_n22(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AdminResultEntry>): Array<AdminResultEntry> {
    return value.map((x)=>from_candid_AdminResultEntry_n35(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AdminScrambleView>): Array<AdminScrambleView> {
    return value.map((x)=>from_candid_AdminScrambleView_n40(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CompetitionPublic>): Array<CompetitionPublic> {
    return value.map((x)=>from_candid_CompetitionPublic_n43(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_LeaderboardEntry>): Array<LeaderboardEntry> {
    return value.map((x)=>from_candid_LeaderboardEntry_n52(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CompetitionResult>): Array<CompetitionResult> {
    return value.map((x)=>from_candid_CompetitionResult_n58(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserSummary>): Array<UserSummary> {
    return value.map((x)=>from_candid_UserSummary_n63(_uploadFile, _downloadFile, x));
}
function to_candid_CompetitionInput_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CompetitionInput): _CompetitionInput {
    return to_candid_record_n8(_uploadFile, _downloadFile, value);
}
function to_candid_CompetitionStatus_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CompetitionStatus): _CompetitionStatus {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_Event_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Event): _Event {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_FeeMode_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FeeMode): _FeeMode {
    return to_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function to_candid_PaymentConfirmation_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentConfirmation): _PaymentConfirmation {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_RazorpayOrderRequest_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RazorpayOrderRequest): _RazorpayOrderRequest {
    return to_candid_record_n31(_uploadFile, _downloadFile, value);
}
function to_candid_ResultInput_n69(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ResultInput): _ResultInput {
    return to_candid_record_n70(_uploadFile, _downloadFile, value);
}
function to_candid_SolveStatus_n71(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SolveStatus): _SolveStatus {
    return to_candid_variant_n72(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n66(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    event: Event;
    competitionId: bigint;
}): {
    event: _Event;
    competitionId: bigint;
} {
    return {
        event: to_candid_Event_n5(_uploadFile, _downloadFile, value.event),
        competitionId: value.competitionId
    };
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    razorpayPaymentId: string;
    razorpaySignature: string;
    event: Event;
    razorpayOrderId: string;
    competitionId: bigint;
}): {
    razorpayPaymentId: string;
    razorpaySignature: string;
    event: _Event;
    razorpayOrderId: string;
    competitionId: bigint;
} {
    return {
        razorpayPaymentId: value.razorpayPaymentId,
        razorpaySignature: value.razorpaySignature,
        event: to_candid_Event_n5(_uploadFile, _downloadFile, value.event),
        razorpayOrderId: value.razorpayOrderId,
        competitionId: value.competitionId
    };
}
function to_candid_record_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    country?: string;
    displayName: string;
    gender?: string;
    mcubesId: string;
}): {
    country: [] | [string];
    displayName: string;
    gender: [] | [string];
    mcubesId: string;
} {
    return {
        country: value.country ? candid_some(value.country) : candid_none(),
        displayName: value.displayName,
        gender: value.gender ? candid_some(value.gender) : candid_none(),
        mcubesId: value.mcubesId
    };
}
function to_candid_record_n70(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ao5?: bigint;
    status: SolveStatus;
    user: Principal;
    attempts: Array<AttemptInput>;
    event: Event;
    competitionId: bigint;
}): {
    ao5: [] | [bigint];
    status: _SolveStatus;
    user: Principal;
    attempts: Array<_AttemptInput>;
    event: _Event;
    competitionId: bigint;
} {
    return {
        ao5: value.ao5 ? candid_some(value.ao5) : candid_none(),
        status: to_candid_SolveStatus_n71(_uploadFile, _downloadFile, value.status),
        user: value.user,
        attempts: value.attempts,
        event: to_candid_Event_n5(_uploadFile, _downloadFile, value.event),
        competitionId: value.competitionId
    };
}
function to_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: CompetitionStatus;
    endDate: Time;
    scrambles: Array<[Array<string>, Event]>;
    name: string;
    slug: string;
    feeMode?: FeeMode;
    events: Array<Event>;
    participantLimit?: bigint;
    registrationStartDate?: Time;
    startDate: Time;
}): {
    status: _CompetitionStatus;
    endDate: _Time;
    scrambles: Array<[Array<string>, _Event]>;
    name: string;
    slug: string;
    feeMode: [] | [_FeeMode];
    events: Array<_Event>;
    participantLimit: [] | [bigint];
    registrationStartDate: [] | [_Time];
    startDate: _Time;
} {
    return {
        status: to_candid_CompetitionStatus_n9(_uploadFile, _downloadFile, value.status),
        endDate: value.endDate,
        scrambles: to_candid_vec_n11(_uploadFile, _downloadFile, value.scrambles),
        name: value.name,
        slug: value.slug,
        feeMode: value.feeMode ? candid_some(to_candid_FeeMode_n13(_uploadFile, _downloadFile, value.feeMode)) : candid_none(),
        events: to_candid_vec_n15(_uploadFile, _downloadFile, value.events),
        participantLimit: value.participantLimit ? candid_some(value.participantLimit) : candid_none(),
        registrationStartDate: value.registrationStartDate ? candid_some(value.registrationStartDate) : candid_none(),
        startDate: value.startDate
    };
}
function to_candid_tuple_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [Array<string>, Event]): [Array<string>, _Event] {
    return [
        value[0],
        to_candid_Event_n5(_uploadFile, _downloadFile, value[1])
    ];
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CompetitionStatus): {
    upcoming: null;
} | {
    completed: null;
} | {
    running: null;
} {
    return value == CompetitionStatus.upcoming ? {
        upcoming: null
    } : value == CompetitionStatus.completed ? {
        completed: null
    } : value == CompetitionStatus.running ? {
        running: null
    } : value;
}
function to_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "perEvent";
    perEvent: bigint;
} | {
    __kind__: "allEventsFlat";
    allEventsFlat: bigint;
} | {
    __kind__: "basePlusAdditional";
    basePlusAdditional: {
        baseFee: bigint;
        additionalFee: bigint;
    };
}): {
    perEvent: bigint;
} | {
    allEventsFlat: bigint;
} | {
    basePlusAdditional: {
        baseFee: bigint;
        additionalFee: bigint;
    };
} {
    return value.__kind__ === "perEvent" ? {
        perEvent: value.perEvent
    } : value.__kind__ === "allEventsFlat" ? {
        allEventsFlat: value.allEventsFlat
    } : value.__kind__ === "basePlusAdditional" ? {
        basePlusAdditional: value.basePlusAdditional
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Event): {
    megaminx: null;
} | {
    fiveByFive: null;
} | {
    threeByThreeOneHanded: null;
} | {
    clock: null;
} | {
    threeByThree: null;
} | {
    pyraminx: null;
} | {
    skewb: null;
} | {
    twoByTwo: null;
} | {
    fourByFour: null;
} {
    return value == Event.megaminx ? {
        megaminx: null
    } : value == Event.fiveByFive ? {
        fiveByFive: null
    } : value == Event.threeByThreeOneHanded ? {
        threeByThreeOneHanded: null
    } : value == Event.clock ? {
        clock: null
    } : value == Event.threeByThree ? {
        threeByThree: null
    } : value == Event.pyraminx ? {
        pyraminx: null
    } : value == Event.skewb ? {
        skewb: null
    } : value == Event.twoByTwo ? {
        twoByTwo: null
    } : value == Event.fourByFour ? {
        fourByFour: null
    } : value;
}
function to_candid_variant_n72(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SolveStatus): {
    in_progress: null;
} | {
    completed: null;
} | {
    not_started: null;
} {
    return value == SolveStatus.in_progress ? {
        in_progress: null
    } : value == SolveStatus.completed ? {
        completed: null
    } : value == SolveStatus.not_started ? {
        not_started: null
    } : value;
}
function to_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[Array<string>, Event]>): Array<[Array<string>, _Event]> {
    return value.map((x)=>to_candid_tuple_n12(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Event>): Array<_Event> {
    return value.map((x)=>to_candid_Event_n5(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
