/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface LeaderboardEntry {
    bestTime: bigint;
    user: Principal;
    attempts: Array<Attempt>;
    userProfile?: PublicProfileInfo;
}
export interface CompetitionInput {
    status: CompetitionStatus;
    endDate: Time;
    scrambles: Array<[Array<string>, Event]>;
    name: string;
    slug: string;
    events: Array<Event>;
    entryFee?: bigint;
    participantLimit?: bigint;
    startDate: Time;
}
export type Time = bigint;
export interface PublicProfileInfo {
    country?: string;
    displayName: string;
    gender?: string;
}
export interface RazorpayOrderRequest {
    event: Event;
    competitionId: bigint;
}
export interface SessionStateResponse {
    startTime?: bigint;
    isCompleted: boolean;
    endTime?: bigint;
    currentAttempt: bigint;
    attempts: Array<Attempt>;
    event: Event;
    inspectionStarted: boolean;
}
export interface CompetitionResult {
    status: SolveStatus;
    user: Principal;
    attempts: Array<Attempt>;
    event: Event;
    userProfile?: UserProfile;
}
export interface CompetitionPublic {
    id: bigint;
    status: CompetitionStatus;
    endDate: Time;
    name: string;
    slug: string;
    events: Array<Event>;
    entryFee?: bigint;
    participantLimit?: bigint;
    startDate: Time;
}
export interface AttemptInput {
    penalty: bigint;
    time: bigint;
}
export interface PaymentConfirmation {
    razorpayPaymentId: string;
    razorpaySignature: string;
    event: Event;
    razorpayOrderId: string;
    competitionId: bigint;
}
export interface RazorpayOrderResponse {
    orderId: string;
    event: Event;
    currency: string;
    amount: bigint;
    competitionName: string;
}
export interface Result {
    status: SolveStatus;
    user: Principal;
    attempts: Array<Attempt>;
    event: Event;
    competitionId: bigint;
}
export interface UserSummary {
    principal: Principal;
    isBlocked: boolean;
    email?: string;
    profile?: UserProfile;
}
export interface Competition {
    id: bigint;
    status: CompetitionStatus;
    endDate: Time;
    scrambles: Array<[Array<string>, Event]>;
    name: string;
    slug: string;
    isActive: boolean;
    events: Array<Event>;
    isLocked: boolean;
    entryFee?: bigint;
    participantLimit?: bigint;
    startDate: Time;
}
export interface AdminLeaderboardToggleResult {
    user: Principal;
    event: Event;
    isHidden: boolean;
    competitionId: bigint;
}
export interface Attempt {
    penalty: bigint;
    time: bigint;
}
export interface UserProfile {
    country?: string;
    displayName: string;
    gender?: string;
    mcubesId: string;
}
export enum CompetitionStatus {
    upcoming = "upcoming",
    completed = "completed",
    running = "running"
}
export enum Event {
    megaminx = "megaminx",
    fiveByFive = "fiveByFive",
    threeByThreeOneHanded = "threeByThreeOneHanded",
    clock = "clock",
    threeByThree = "threeByThree",
    pyraminx = "pyraminx",
    skewb = "skewb",
    twoByTwo = "twoByTwo",
    fourByFour = "fourByFour"
}
export enum SolveStatus {
    in_progress = "in_progress",
    completed = "completed",
    not_started = "not_started"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    activateCompetition(id: bigint): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    blockUser(user: Principal): Promise<void>;
    confirmPayment(payment: PaymentConfirmation): Promise<void>;
    createCompetition(compInput: CompetitionInput): Promise<bigint>;
    createRazorpayOrder(request: RazorpayOrderRequest): Promise<RazorpayOrderResponse>;
    createUserProfile(displayName: string, country: string | null, gender: string | null): Promise<void>;
    deactivateCompetition(id: bigint): Promise<void>;
    deleteCompetition(id: bigint): Promise<void>;
    deleteUser(user: Principal): Promise<void>;
    duplicateCompetition(id: bigint): Promise<bigint>;
    generateSecureToken(): Promise<Uint8Array>;
    getCallerResult(competitionId: bigint, event: Event): Promise<Result | null>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCompetition(id: bigint): Promise<Competition | null>;
    getCompetitions(): Promise<Array<CompetitionPublic>>;
    getLeaderboard(competitionId: bigint, event: Event): Promise<Array<LeaderboardEntry>>;
    getPublicProfileInfo(user: Principal): Promise<PublicProfileInfo | null>;
    getPublicResultsForUser(user: Principal, includeHidden: boolean): Promise<{
        results: Array<CompetitionResult>;
        profile?: PublicProfileInfo;
    }>;
    getRazorpayKeyId(): Promise<string | null>;
    getScramble(competitionId: bigint, event: Event, attemptNumber: bigint, sessionToken: Uint8Array): Promise<string | null>;
    getSessionState(competitionId: bigint, event: Event): Promise<SessionStateResponse | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    isRazorpayConfigured(): Promise<boolean>;
    listAllUsers(): Promise<Array<UserSummary>>;
    listCompetitionResults(competitionId: bigint, event: Event): Promise<Array<CompetitionResult>>;
    lockCompetition(id: bigint): Promise<void>;
    resetUserCompetitionStatus(user: Principal, competitionId: bigint, event: Event): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setRazorpayCredentials(keyId: string, keySecret: string): Promise<void>;
    setUserEmail(email: string): Promise<void>;
    startCompetition(competitionId: bigint, event: Event): Promise<Uint8Array>;
    submitAttempt(competitionId: bigint, event: Event, attemptNumber: bigint, time: bigint, penalty: bigint, sessionToken: Uint8Array): Promise<void>;
    toggleLeaderboardEntryVisibility(user: Principal, competitionId: bigint, event: Event, shouldHide: boolean): Promise<AdminLeaderboardToggleResult>;
    unblockUser(user: Principal): Promise<void>;
    unlockCompetition(id: bigint): Promise<void>;
    updateCompetition(id: bigint, compInput: CompetitionInput): Promise<void>;
    updateResultAttempts(user: Principal, competitionId: bigint, event: Event, attempts: Array<AttemptInput>): Promise<void>;
}
import type { AdminLeaderboardToggleResult as _AdminLeaderboardToggleResult, Attempt as _Attempt, Competition as _Competition, CompetitionInput as _CompetitionInput, CompetitionPublic as _CompetitionPublic, CompetitionResult as _CompetitionResult, CompetitionStatus as _CompetitionStatus, Event as _Event, LeaderboardEntry as _LeaderboardEntry, PaymentConfirmation as _PaymentConfirmation, PublicProfileInfo as _PublicProfileInfo, RazorpayOrderRequest as _RazorpayOrderRequest, RazorpayOrderResponse as _RazorpayOrderResponse, Result as _Result, SessionStateResponse as _SessionStateResponse, SolveStatus as _SolveStatus, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, UserSummary as _UserSummary } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async activateCompetition(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.activateCompetition(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.activateCompetition(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async blockUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.blockUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.blockUser(arg0);
            return result;
        }
    }
    async confirmPayment(arg0: PaymentConfirmation): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.confirmPayment(to_candid_PaymentConfirmation_n3(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.confirmPayment(to_candid_PaymentConfirmation_n3(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createCompetition(arg0: CompetitionInput): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createCompetition(to_candid_CompetitionInput_n7(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCompetition(to_candid_CompetitionInput_n7(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createRazorpayOrder(arg0: RazorpayOrderRequest): Promise<RazorpayOrderResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.createRazorpayOrder(to_candid_RazorpayOrderRequest_n14(this._uploadFile, this._downloadFile, arg0));
                return from_candid_RazorpayOrderResponse_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createRazorpayOrder(to_candid_RazorpayOrderRequest_n14(this._uploadFile, this._downloadFile, arg0));
            return from_candid_RazorpayOrderResponse_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async createUserProfile(arg0: string, arg1: string | null, arg2: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createUserProfile(arg0, to_candid_opt_n20(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n20(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createUserProfile(arg0, to_candid_opt_n20(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n20(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async deactivateCompetition(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deactivateCompetition(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deactivateCompetition(arg0);
            return result;
        }
    }
    async deleteCompetition(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCompetition(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCompetition(arg0);
            return result;
        }
    }
    async deleteUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteUser(arg0);
            return result;
        }
    }
    async duplicateCompetition(arg0: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.duplicateCompetition(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.duplicateCompetition(arg0);
            return result;
        }
    }
    async generateSecureToken(): Promise<Uint8Array> {
        if (this.processError) {
            try {
                const result = await this.actor.generateSecureToken();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateSecureToken();
            return result;
        }
    }
    async getCallerResult(arg0: bigint, arg1: Event): Promise<Result | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerResult(arg0, to_candid_Event_n5(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerResult(arg0, to_candid_Event_n5(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCompetition(arg0: bigint): Promise<Competition | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCompetition(arg0);
                return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCompetition(arg0);
            return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCompetitions(): Promise<Array<CompetitionPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCompetitions();
                return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCompetitions();
            return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLeaderboard(arg0: bigint, arg1: Event): Promise<Array<LeaderboardEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeaderboard(arg0, to_candid_Event_n5(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeaderboard(arg0, to_candid_Event_n5(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPublicProfileInfo(arg0: Principal): Promise<PublicProfileInfo | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublicProfileInfo(arg0);
                return from_candid_opt_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublicProfileInfo(arg0);
            return from_candid_opt_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPublicResultsForUser(arg0: Principal, arg1: boolean): Promise<{
        results: Array<CompetitionResult>;
        profile?: PublicProfileInfo;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublicResultsForUser(arg0, arg1);
                return from_candid_record_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublicResultsForUser(arg0, arg1);
            return from_candid_record_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRazorpayKeyId(): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getRazorpayKeyId();
                return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRazorpayKeyId();
            return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getScramble(arg0: bigint, arg1: Event, arg2: bigint, arg3: Uint8Array): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getScramble(arg0, to_candid_Event_n5(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
                return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getScramble(arg0, to_candid_Event_n5(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
            return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSessionState(arg0: bigint, arg1: Event): Promise<SessionStateResponse | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSessionState(arg0, to_candid_Event_n5(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n54(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSessionState(arg0, to_candid_Event_n5(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n54(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isRazorpayConfigured(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isRazorpayConfigured();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isRazorpayConfigured();
            return result;
        }
    }
    async listAllUsers(): Promise<Array<UserSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllUsers();
                return from_candid_vec_n57(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllUsers();
            return from_candid_vec_n57(this._uploadFile, this._downloadFile, result);
        }
    }
    async listCompetitionResults(arg0: bigint, arg1: Event): Promise<Array<CompetitionResult>> {
        if (this.processError) {
            try {
                const result = await this.actor.listCompetitionResults(arg0, to_candid_Event_n5(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listCompetitionResults(arg0, to_candid_Event_n5(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async lockCompetition(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.lockCompetition(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.lockCompetition(arg0);
            return result;
        }
    }
    async resetUserCompetitionStatus(arg0: Principal, arg1: bigint, arg2: Event): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.resetUserCompetitionStatus(arg0, arg1, to_candid_Event_n5(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resetUserCompetitionStatus(arg0, arg1, to_candid_Event_n5(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n60(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n60(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setRazorpayCredentials(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setRazorpayCredentials(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setRazorpayCredentials(arg0, arg1);
            return result;
        }
    }
    async setUserEmail(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setUserEmail(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setUserEmail(arg0);
            return result;
        }
    }
    async startCompetition(arg0: bigint, arg1: Event): Promise<Uint8Array> {
        if (this.processError) {
            try {
                const result = await this.actor.startCompetition(arg0, to_candid_Event_n5(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.startCompetition(arg0, to_candid_Event_n5(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async submitAttempt(arg0: bigint, arg1: Event, arg2: bigint, arg3: bigint, arg4: bigint, arg5: Uint8Array): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitAttempt(arg0, to_candid_Event_n5(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitAttempt(arg0, to_candid_Event_n5(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async toggleLeaderboardEntryVisibility(arg0: Principal, arg1: bigint, arg2: Event, arg3: boolean): Promise<AdminLeaderboardToggleResult> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleLeaderboardEntryVisibility(arg0, arg1, to_candid_Event_n5(this._uploadFile, this._downloadFile, arg2), arg3);
                return from_candid_AdminLeaderboardToggleResult_n62(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleLeaderboardEntryVisibility(arg0, arg1, to_candid_Event_n5(this._uploadFile, this._downloadFile, arg2), arg3);
            return from_candid_AdminLeaderboardToggleResult_n62(this._uploadFile, this._downloadFile, result);
        }
    }
    async unblockUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unblockUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unblockUser(arg0);
            return result;
        }
    }
    async unlockCompetition(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unlockCompetition(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unlockCompetition(arg0);
            return result;
        }
    }
    async updateCompetition(arg0: bigint, arg1: CompetitionInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCompetition(arg0, to_candid_CompetitionInput_n7(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCompetition(arg0, to_candid_CompetitionInput_n7(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateResultAttempts(arg0: Principal, arg1: bigint, arg2: Event, arg3: Array<AttemptInput>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateResultAttempts(arg0, arg1, to_candid_Event_n5(this._uploadFile, this._downloadFile, arg2), arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateResultAttempts(arg0, arg1, to_candid_Event_n5(this._uploadFile, this._downloadFile, arg2), arg3);
            return result;
        }
    }
}
function from_candid_AdminLeaderboardToggleResult_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AdminLeaderboardToggleResult): AdminLeaderboardToggleResult {
    return from_candid_record_n63(_uploadFile, _downloadFile, value);
}
function from_candid_CompetitionPublic_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CompetitionPublic): CompetitionPublic {
    return from_candid_record_n43(_uploadFile, _downloadFile, value);
}
function from_candid_CompetitionResult_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CompetitionResult): CompetitionResult {
    return from_candid_record_n53(_uploadFile, _downloadFile, value);
}
function from_candid_CompetitionStatus_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CompetitionStatus): CompetitionStatus {
    return from_candid_variant_n36(_uploadFile, _downloadFile, value);
}
function from_candid_Competition_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Competition): Competition {
    return from_candid_record_n34(_uploadFile, _downloadFile, value);
}
function from_candid_Event_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Event): Event {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_LeaderboardEntry_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LeaderboardEntry): LeaderboardEntry {
    return from_candid_record_n46(_uploadFile, _downloadFile, value);
}
function from_candid_PublicProfileInfo_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PublicProfileInfo): PublicProfileInfo {
    return from_candid_record_n49(_uploadFile, _downloadFile, value);
}
function from_candid_RazorpayOrderResponse_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RazorpayOrderResponse): RazorpayOrderResponse {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_SessionStateResponse_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SessionStateResponse): SessionStateResponse {
    return from_candid_record_n56(_uploadFile, _downloadFile, value);
}
function from_candid_SolveStatus_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SolveStatus): SolveStatus {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function from_candid_UserSummary_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserSummary): UserSummary {
    return from_candid_record_n59(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Result]): Result | null {
    return value.length === 0 ? null : from_candid_Result_n22(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n27(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Competition]): Competition | null {
    return value.length === 0 ? null : from_candid_Competition_n33(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PublicProfileInfo]): PublicProfileInfo | null {
    return value.length === 0 ? null : from_candid_PublicProfileInfo_n48(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SessionStateResponse]): SessionStateResponse | null {
    return value.length === 0 ? null : from_candid_SessionStateResponse_n55(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    orderId: string;
    event: _Event;
    currency: string;
    amount: bigint;
    competitionName: string;
}): {
    orderId: string;
    event: Event;
    currency: string;
    amount: bigint;
    competitionName: string;
} {
    return {
        orderId: value.orderId,
        event: from_candid_Event_n18(_uploadFile, _downloadFile, value.event),
        currency: value.currency,
        amount: value.amount,
        competitionName: value.competitionName
    };
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _SolveStatus;
    user: Principal;
    attempts: Array<_Attempt>;
    event: _Event;
    competitionId: bigint;
}): {
    status: SolveStatus;
    user: Principal;
    attempts: Array<Attempt>;
    event: Event;
    competitionId: bigint;
} {
    return {
        status: from_candid_SolveStatus_n24(_uploadFile, _downloadFile, value.status),
        user: value.user,
        attempts: value.attempts,
        event: from_candid_Event_n18(_uploadFile, _downloadFile, value.event),
        competitionId: value.competitionId
    };
}
function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    country: [] | [string];
    displayName: string;
    gender: [] | [string];
    mcubesId: string;
}): {
    country?: string;
    displayName: string;
    gender?: string;
    mcubesId: string;
} {
    return {
        country: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.country)),
        displayName: value.displayName,
        gender: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.gender)),
        mcubesId: value.mcubesId
    };
}
function from_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _CompetitionStatus;
    endDate: _Time;
    scrambles: Array<[Array<string>, _Event]>;
    name: string;
    slug: string;
    isActive: boolean;
    events: Array<_Event>;
    isLocked: boolean;
    entryFee: [] | [bigint];
    participantLimit: [] | [bigint];
    startDate: _Time;
}): {
    id: bigint;
    status: CompetitionStatus;
    endDate: Time;
    scrambles: Array<[Array<string>, Event]>;
    name: string;
    slug: string;
    isActive: boolean;
    events: Array<Event>;
    isLocked: boolean;
    entryFee?: bigint;
    participantLimit?: bigint;
    startDate: Time;
} {
    return {
        id: value.id,
        status: from_candid_CompetitionStatus_n35(_uploadFile, _downloadFile, value.status),
        endDate: value.endDate,
        scrambles: from_candid_vec_n37(_uploadFile, _downloadFile, value.scrambles),
        name: value.name,
        slug: value.slug,
        isActive: value.isActive,
        events: from_candid_vec_n39(_uploadFile, _downloadFile, value.events),
        isLocked: value.isLocked,
        entryFee: record_opt_to_undefined(from_candid_opt_n40(_uploadFile, _downloadFile, value.entryFee)),
        participantLimit: record_opt_to_undefined(from_candid_opt_n40(_uploadFile, _downloadFile, value.participantLimit)),
        startDate: value.startDate
    };
}
function from_candid_record_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _CompetitionStatus;
    endDate: _Time;
    name: string;
    slug: string;
    events: Array<_Event>;
    entryFee: [] | [bigint];
    participantLimit: [] | [bigint];
    startDate: _Time;
}): {
    id: bigint;
    status: CompetitionStatus;
    endDate: Time;
    name: string;
    slug: string;
    events: Array<Event>;
    entryFee?: bigint;
    participantLimit?: bigint;
    startDate: Time;
} {
    return {
        id: value.id,
        status: from_candid_CompetitionStatus_n35(_uploadFile, _downloadFile, value.status),
        endDate: value.endDate,
        name: value.name,
        slug: value.slug,
        events: from_candid_vec_n39(_uploadFile, _downloadFile, value.events),
        entryFee: record_opt_to_undefined(from_candid_opt_n40(_uploadFile, _downloadFile, value.entryFee)),
        participantLimit: record_opt_to_undefined(from_candid_opt_n40(_uploadFile, _downloadFile, value.participantLimit)),
        startDate: value.startDate
    };
}
function from_candid_record_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bestTime: bigint;
    user: Principal;
    attempts: Array<_Attempt>;
    userProfile: [] | [_PublicProfileInfo];
}): {
    bestTime: bigint;
    user: Principal;
    attempts: Array<Attempt>;
    userProfile?: PublicProfileInfo;
} {
    return {
        bestTime: value.bestTime,
        user: value.user,
        attempts: value.attempts,
        userProfile: record_opt_to_undefined(from_candid_opt_n47(_uploadFile, _downloadFile, value.userProfile))
    };
}
function from_candid_record_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    country: [] | [string];
    displayName: string;
    gender: [] | [string];
}): {
    country?: string;
    displayName: string;
    gender?: string;
} {
    return {
        country: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.country)),
        displayName: value.displayName,
        gender: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.gender))
    };
}
function from_candid_record_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    results: Array<_CompetitionResult>;
    profile: [] | [_PublicProfileInfo];
}): {
    results: Array<CompetitionResult>;
    profile?: PublicProfileInfo;
} {
    return {
        results: from_candid_vec_n51(_uploadFile, _downloadFile, value.results),
        profile: record_opt_to_undefined(from_candid_opt_n47(_uploadFile, _downloadFile, value.profile))
    };
}
function from_candid_record_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _SolveStatus;
    user: Principal;
    attempts: Array<_Attempt>;
    event: _Event;
    userProfile: [] | [_UserProfile];
}): {
    status: SolveStatus;
    user: Principal;
    attempts: Array<Attempt>;
    event: Event;
    userProfile?: UserProfile;
} {
    return {
        status: from_candid_SolveStatus_n24(_uploadFile, _downloadFile, value.status),
        user: value.user,
        attempts: value.attempts,
        event: from_candid_Event_n18(_uploadFile, _downloadFile, value.event),
        userProfile: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.userProfile))
    };
}
function from_candid_record_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    startTime: [] | [bigint];
    isCompleted: boolean;
    endTime: [] | [bigint];
    currentAttempt: bigint;
    attempts: Array<_Attempt>;
    event: _Event;
    inspectionStarted: boolean;
}): {
    startTime?: bigint;
    isCompleted: boolean;
    endTime?: bigint;
    currentAttempt: bigint;
    attempts: Array<Attempt>;
    event: Event;
    inspectionStarted: boolean;
} {
    return {
        startTime: record_opt_to_undefined(from_candid_opt_n40(_uploadFile, _downloadFile, value.startTime)),
        isCompleted: value.isCompleted,
        endTime: record_opt_to_undefined(from_candid_opt_n40(_uploadFile, _downloadFile, value.endTime)),
        currentAttempt: value.currentAttempt,
        attempts: value.attempts,
        event: from_candid_Event_n18(_uploadFile, _downloadFile, value.event),
        inspectionStarted: value.inspectionStarted
    };
}
function from_candid_record_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    principal: Principal;
    isBlocked: boolean;
    email: [] | [string];
    profile: [] | [_UserProfile];
}): {
    principal: Principal;
    isBlocked: boolean;
    email?: string;
    profile?: UserProfile;
} {
    return {
        principal: value.principal,
        isBlocked: value.isBlocked,
        email: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.email)),
        profile: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.profile))
    };
}
function from_candid_record_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    user: Principal;
    event: _Event;
    isHidden: boolean;
    competitionId: bigint;
}): {
    user: Principal;
    event: Event;
    isHidden: boolean;
    competitionId: bigint;
} {
    return {
        user: value.user,
        event: from_candid_Event_n18(_uploadFile, _downloadFile, value.event),
        isHidden: value.isHidden,
        competitionId: value.competitionId
    };
}
function from_candid_tuple_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [Array<string>, _Event]): [Array<string>, Event] {
    return [
        value[0],
        from_candid_Event_n18(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    megaminx: null;
} | {
    fiveByFive: null;
} | {
    threeByThreeOneHanded: null;
} | {
    clock: null;
} | {
    threeByThree: null;
} | {
    pyraminx: null;
} | {
    skewb: null;
} | {
    twoByTwo: null;
} | {
    fourByFour: null;
}): Event {
    return "megaminx" in value ? Event.megaminx : "fiveByFive" in value ? Event.fiveByFive : "threeByThreeOneHanded" in value ? Event.threeByThreeOneHanded : "clock" in value ? Event.clock : "threeByThree" in value ? Event.threeByThree : "pyraminx" in value ? Event.pyraminx : "skewb" in value ? Event.skewb : "twoByTwo" in value ? Event.twoByTwo : "fourByFour" in value ? Event.fourByFour : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    in_progress: null;
} | {
    completed: null;
} | {
    not_started: null;
}): SolveStatus {
    return "in_progress" in value ? SolveStatus.in_progress : "completed" in value ? SolveStatus.completed : "not_started" in value ? SolveStatus.not_started : value;
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    upcoming: null;
} | {
    completed: null;
} | {
    running: null;
}): CompetitionStatus {
    return "upcoming" in value ? CompetitionStatus.upcoming : "completed" in value ? CompetitionStatus.completed : "running" in value ? CompetitionStatus.running : value;
}
function from_candid_vec_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[Array<string>, _Event]>): Array<[Array<string>, Event]> {
    return value.map((x)=>from_candid_tuple_n38(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Event>): Array<Event> {
    return value.map((x)=>from_candid_Event_n18(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CompetitionPublic>): Array<CompetitionPublic> {
    return value.map((x)=>from_candid_CompetitionPublic_n42(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_LeaderboardEntry>): Array<LeaderboardEntry> {
    return value.map((x)=>from_candid_LeaderboardEntry_n45(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CompetitionResult>): Array<CompetitionResult> {
    return value.map((x)=>from_candid_CompetitionResult_n52(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserSummary>): Array<UserSummary> {
    return value.map((x)=>from_candid_UserSummary_n58(_uploadFile, _downloadFile, x));
}
function to_candid_CompetitionInput_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CompetitionInput): _CompetitionInput {
    return to_candid_record_n8(_uploadFile, _downloadFile, value);
}
function to_candid_CompetitionStatus_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CompetitionStatus): _CompetitionStatus {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_Event_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Event): _Event {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_PaymentConfirmation_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentConfirmation): _PaymentConfirmation {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_RazorpayOrderRequest_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RazorpayOrderRequest): _RazorpayOrderRequest {
    return to_candid_record_n15(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n61(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    event: Event;
    competitionId: bigint;
}): {
    event: _Event;
    competitionId: bigint;
} {
    return {
        event: to_candid_Event_n5(_uploadFile, _downloadFile, value.event),
        competitionId: value.competitionId
    };
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    razorpayPaymentId: string;
    razorpaySignature: string;
    event: Event;
    razorpayOrderId: string;
    competitionId: bigint;
}): {
    razorpayPaymentId: string;
    razorpaySignature: string;
    event: _Event;
    razorpayOrderId: string;
    competitionId: bigint;
} {
    return {
        razorpayPaymentId: value.razorpayPaymentId,
        razorpaySignature: value.razorpaySignature,
        event: to_candid_Event_n5(_uploadFile, _downloadFile, value.event),
        razorpayOrderId: value.razorpayOrderId,
        competitionId: value.competitionId
    };
}
function to_candid_record_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    country?: string;
    displayName: string;
    gender?: string;
    mcubesId: string;
}): {
    country: [] | [string];
    displayName: string;
    gender: [] | [string];
    mcubesId: string;
} {
    return {
        country: value.country ? candid_some(value.country) : candid_none(),
        displayName: value.displayName,
        gender: value.gender ? candid_some(value.gender) : candid_none(),
        mcubesId: value.mcubesId
    };
}
function to_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: CompetitionStatus;
    endDate: Time;
    scrambles: Array<[Array<string>, Event]>;
    name: string;
    slug: string;
    events: Array<Event>;
    entryFee?: bigint;
    participantLimit?: bigint;
    startDate: Time;
}): {
    status: _CompetitionStatus;
    endDate: _Time;
    scrambles: Array<[Array<string>, _Event]>;
    name: string;
    slug: string;
    events: Array<_Event>;
    entryFee: [] | [bigint];
    participantLimit: [] | [bigint];
    startDate: _Time;
} {
    return {
        status: to_candid_CompetitionStatus_n9(_uploadFile, _downloadFile, value.status),
        endDate: value.endDate,
        scrambles: to_candid_vec_n11(_uploadFile, _downloadFile, value.scrambles),
        name: value.name,
        slug: value.slug,
        events: to_candid_vec_n13(_uploadFile, _downloadFile, value.events),
        entryFee: value.entryFee ? candid_some(value.entryFee) : candid_none(),
        participantLimit: value.participantLimit ? candid_some(value.participantLimit) : candid_none(),
        startDate: value.startDate
    };
}
function to_candid_tuple_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [Array<string>, Event]): [Array<string>, _Event] {
    return [
        value[0],
        to_candid_Event_n5(_uploadFile, _downloadFile, value[1])
    ];
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CompetitionStatus): {
    upcoming: null;
} | {
    completed: null;
} | {
    running: null;
} {
    return value == CompetitionStatus.upcoming ? {
        upcoming: null
    } : value == CompetitionStatus.completed ? {
        completed: null
    } : value == CompetitionStatus.running ? {
        running: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Event): {
    megaminx: null;
} | {
    fiveByFive: null;
} | {
    threeByThreeOneHanded: null;
} | {
    clock: null;
} | {
    threeByThree: null;
} | {
    pyraminx: null;
} | {
    skewb: null;
} | {
    twoByTwo: null;
} | {
    fourByFour: null;
} {
    return value == Event.megaminx ? {
        megaminx: null
    } : value == Event.fiveByFive ? {
        fiveByFive: null
    } : value == Event.threeByThreeOneHanded ? {
        threeByThreeOneHanded: null
    } : value == Event.clock ? {
        clock: null
    } : value == Event.threeByThree ? {
        threeByThree: null
    } : value == Event.pyraminx ? {
        pyraminx: null
    } : value == Event.skewb ? {
        skewb: null
    } : value == Event.twoByTwo ? {
        twoByTwo: null
    } : value == Event.fourByFour ? {
        fourByFour: null
    } : value;
}
function to_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[Array<string>, Event]>): Array<[Array<string>, _Event]> {
    return value.map((x)=>to_candid_tuple_n12(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Event>): Array<_Event> {
    return value.map((x)=>to_candid_Event_n5(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
